### ISSUE TITLE
Hello, can you provide code in the "Explore Fast Locate USING Text"？  Thank you very much！

### ISSUE THREAD

**Issue by LY080835** [xiaoyuan1996/AMFMN#1]

**Comment by xiaoyuan1996** [comment]
Sorry for the late reply.

Please see the link above

https://github.com/xiaoyuan1996/SemanticLocalizationMetrics

**Comment by LY080835** [comment]
thank you! Your article and code have inspired me a lot, thank you! 
Hope you go well in scientific research!
