### ISSUE TITLE
In the Paper's comparison experiments, is SCAN and CAMP's Resnet-18 pre-training on ImageNet? Or is other pre -training models loading?

### ISSUE THREAD

**Issue by LY080835** [xiaoyuan1996/AMFMN#2]
Each image input of the CAMP and SCAN models is 36 regional features. If you use ResNet18 for feature extraction, how to get these 36 regional features?

**Comment by xiaoyuan1996** [comment]
In the article ,we have mentioned that for methods such as SCAN, we use the feature map of the penultimate layer extracted by the backbone to act as multiple features in the original method.
