### ISSUE TITLE
about file path

### ISSUE THREAD

**Issue by zyuanzi** [xiaoyuan1996/AMFMN#5]
this question came up during training：
[Errno 2] No such file or directory: '/seq2vec/dictionary.txt'

My path is set to：
dir_st: '/seq2vec/'
data_path: 'data/rsitmd_precomp/'
image_path: '/data/rsitmd_precomp/images/'

Also already downloaded ‘dictionary.txt’ ，Placed in a folder '/seq2vec/'

How do I need to fix this？

**Comment by xiaoyuan1996** [comment]
Look at the error message, it should prompt where this file is missing
